apiVersion: apps/v1
kind: Deployment
metadata:
  name: testlink
spec:
  selector:
    matchLabels:
      app: testlink
  template:
    metadata:
      labels:
        app: testlink
    spec:
      containers:
        - name: testlink
          image: tminai/testlink:latest
          command: ["/bin/sh", "-c"]
          args: ["php-fpm && httpd -D FOREGROUND"]
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_USER
              value: "testlinkuser"
            - name: DB_PASSWORD
              value: "testlink_password"
            - name: DB_NAME
              value: "testlinkdb"
          ports:
            - containerPort: 80