apiVersion: apps/v1
kind: Deployment
metadata:
  name: testlink
spec:
  selector:
    matchLabels:
      app: testlink
  template:
    metadata:
      labels:
        app: testlink
    spec:
      containers:
        - name: testlink
          image: fjudith/testlink:latest
          env:
            - name: MYSQL_USER
              value: "testlink_user"
            - name: MYSQL_PASSWORD
              value: "testlink_password"
            - name: MYSQL_DATABASE
              value: "testlink_db"
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: testlink-data
              mountPath: /var/www/html
      volumes:
        - name: testlink-data
          persistentVolumeClaim:
            claimName: testlink-pvc