apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb/mariadb-deployment.yaml
  - mariadb/mariadb-pvc.yaml
  - mariadb/mariadb-svc.yaml
  - web-app/kiwi-deployment.yaml
  - web-app/kiwi-pvc.yaml
  - web-app/kiwi-svc.yaml