apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:latest
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "root_password" # Тільки для локальної розробки!
            - name: MARIADB_USER
              value: "testlinkuser"
            - name: MARIADB_PASSWORD
              value: "testlink_password"
            - name: MARIADB_DATABASE
              value: "testlinkdb"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-pvc