apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-mariadb
  namespace: testing
spec:
  selector:
    matchLabels:
      app: kiwi-mariadb
  template:
    metadata:
      labels:
        app: kiwi-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "root_password"
            - name: MARIADB_DATABASE
              value: "kiwidb"
            - name: MARIADB_USER
              value: "kiwiuser"
            - name: MARIADB_PASSWORD
              value: "kiwipass"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: kiwi-db-pvc