apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: alloy
    targetRevision: 0.1.1 
    helm:
      values: |
        alloy:
          configMap:
            create: true
            content: |
              discovery.kubernetes "pods" {
                role = "pod"
              }

              discovery.relabel "pods" {
                targets = discovery.kubernetes.pods.targets
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app"]
                  target_label  = "app"
                }
              }

              loki.source.kubernetes "local_pods" {
                targets    = discovery.relabel.pods.output
                forward_to = [loki.write.loki_backend.receiver]
              }

              loki.write "loki_backend" {
                endpoint {
                  url = "http://loki-stack.monitoring.svc.cluster.local:3100/loki/api/v1/push"
                }
              }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true