apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiwi-tcms
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/OleksiiTaran/argocd-delivery.git'
    targetRevision: HEAD
    path: apps/kiwi-tcms  # Шлях до твоєї папки з маніфестами
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testing # Краще виділити окремий неймспейс
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true